# Generated by Django 6.0.6 on 2026-06-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_insights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='cell',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='duplicate_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='economic_impact',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='environmental_impact',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='estimated_people_affected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='estimated_resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='public_safety_risk',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='reasoning',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='similar_report_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='similarity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='urgency',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Within 24 Hours', 'Within 24 Hours'), ('Within 3 Days', 'Within 3 Days'), ('Routine', 'Routine')], default='Routine', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Infrastructure', 'Infrastructure'), ('Safety', 'Safety'), ('Utilities', 'Utilities'), ('Environment', 'Environment'), ('Health', 'Health'), ('Transport', 'Transport'), ('Education', 'Education'), ('Security', 'Security'), ('Other', 'Other')], default='Infrastructure', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10),
        ),
    ]
